'use strict';
const research=require('../content/research.json');
const escape=s=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
function researchHTML(){const d=research.dimensions;return `<section id="research" class="dark"><div class="wrap">
<div class="kicker">Research / 01</div><h2 class="h1">A correct answer is only<br>one part of reliability.</h2>
<div class="research-grid"><div><span class="research-tag">${research.status}</span><h3 class="research-statement">MAREF: ${research.expansion}</h3><p class="research-copy">My framework proposal asks a broader question: can an agent answer correctly, stay grounded, follow instructions, behave consistently, and finish the task?</p><p class="research-copy" style="margin-top:18px">The six dimensions below separate failure modes that a single accuracy score can hide. Select a dimension to explore its evaluation approach.</p><div class="research-path" aria-label="Proposed evaluation workflow"><span>Task + reference</span><i>→</i><span>Agent trace</span><i>→</i><span>Six dimensions</span><i>→</i><span>Human review</span></div><p class="example-label">Illustrative Example — Not Experimental Results</p><p class="research-copy" style="font-size:12px">This interactive explanation contains no measured model comparisons. Benchmark datasets, scoring validation and human agreement remain future work for MAREF.</p><a class="btn btn-o" style="margin-top:24px" href="https://github.com/riteshmamidi0905-lab/llm-eval-framework">Explore the related evaluation code ↗</a></div>
<div><div class="dimensions" role="group" aria-label="MAREF reliability dimensions">${d.map((x,i)=>`<button class="dimension" aria-pressed="${i===0}" data-name="${x.name}" data-flow="${x.flow.join('|')}" data-description="${escape(x.question+' '+x.method+' Example: '+x.example)}"><span>0${i+1} / ${x.question}</span>${x.name}</button>`).join('')}</div><div class="dimension-flow" aria-hidden="true">${d[0].flow.map(n=>`<span>${n}</span>`).join('<i>→</i>')}</div><div class="research-detail" aria-live="polite" aria-atomic="true"><h3 id="dimensionTitle">${d[0].name}</h3><p id="dimensionDetail">${d[0].question} ${d[0].method} Example: ${d[0].example}</p></div></div></div></div></section>`}
function watchHTML(){return `<section id="watch" class="paper"><div class="wrap"><div class="kicker">Build notes, in motion</div><h2 class="h1">Watch me explain my work.</h2><div class="watch-heading"><img src="linkedin-avatar.webp" alt="Ritesh Mamidi" width="64" height="64" loading="lazy"><p>Short, captioned explanations of the engineering behind my projects. These diagram-led films are prepared from my repositories; they contain no generated presenter or cloned voice.</p></div><div class="watch-grid">${[
 ['streaming','Real-time signals, explained','35 seconds','realtime-streaming-pipeline','Kafka ingestion, explainable fraud rules, event-time windows and Cassandra serving.'],
 ['evaluation','Measure the answer. Inspect the failure.','40 seconds','llm-eval-framework','Why weighted rubrics and hard gates belong in the same evaluation system.'],
 ['rag','From a question to a cited answer','40 seconds','genai-doc-assistant','Chunking, retrieval, grounded extractive answers and abstention in the offline path.']
].map(([id,name,time,repo,desc])=>`<article class="watch-card"><video controls preload="none" playsinline poster="assets/media/${id}-poster.webp" aria-label="${name}"><source src="assets/media/${id}-teaser.mp4" type="video/mp4"><track kind="captions" src="assets/media/${id}-teaser.vtt" srclang="en" label="English" default>Your browser cannot play this video. <a href="assets/media/${id}-teaser.mp4">Download the captioned video</a>.</video><div class="watch-copy"><div class="watch-meta">${time} · Captioned diagram film</div><h3>${name}</h3><p>${desc}</p><a href="https://github.com/riteshmamidi0905-lab/${repo}">Inspect the repository ↗</a></div></article>`).join('')}</div><div class="watch-deep"><span>Go deeper</span><a href="assets/media/evaluation-explainer.mp4">75-second evaluation explainer ↗</a><a href="assets/media/rag-walkthrough.mp4">3-minute RAG walkthrough ↗</a><span>Diagram demonstrations · Captions embedded · No production telemetry</span></div></div></section>`}
module.exports={researchHTML,watchHTML};
