'use strict';
const research=require('../content/research.json');
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const mediaURL=file=>'assets/media/'+file+'?v='+crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../assets/media',file))).digest('hex').slice(0,12);
const escape=s=>s.replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');
function researchHTML(){const d=research.dimensions;return `<section id="research" class="dark"><div class="wrap">
<div class="kicker">Research / 01</div><h2 class="h1">A correct answer is only<br>one part of reliability.</h2>
<div class="research-grid"><div><span class="research-tag">${research.status}</span><h3 class="research-statement">MAREF: ${research.expansion}</h3><p class="research-copy">My framework proposal asks a broader question: can an agent answer correctly, stay grounded, follow instructions, behave consistently, and finish the task?</p><p class="research-copy" style="margin-top:18px">The six dimensions below separate failure modes that a single accuracy score can hide. Select a dimension to explore its evaluation approach.</p><div class="research-path" aria-label="Proposed evaluation workflow"><span>Task + reference</span><i>→</i><span>Agent trace</span><i>→</i><span>Six dimensions</span><i>→</i><span>Human review</span></div><p class="example-label">Illustrative Example — Not Experimental Results</p><p class="research-copy" style="font-size:12px">This interactive explanation contains no measured model comparisons. Benchmark datasets, scoring validation and human agreement remain future work for MAREF.</p><div class="research-detail"><h3>Proposed benchmark design</h3><p>200 planned tasks: 50 factual/retrieval, 50 analytical reasoning, 50 instruction-following, and 50 multi-step agent tasks. Three repeated trials across three agent configurations would produce 1,800 executions. This is a study plan; these executions have not been reported as completed experiments.</p></div><a class="btn btn-o" style="margin-top:24px" href="https://github.com/riteshmamidi0905-lab/llm-eval-framework">Explore the related evaluation code ↗</a></div>
<div><div class="dimensions" role="group" aria-label="MAREF reliability dimensions">${d.map((x,i)=>`<button class="dimension" aria-pressed="${i===0}" data-name="${x.name}" data-flow="${x.flow.join('|')}" data-description="${escape(x.question+' '+x.method+' Example: '+x.example)}"><span>0${i+1} / ${x.question}</span>${x.name}</button>`).join('')}</div><div class="dimension-flow" aria-hidden="true">${d[0].flow.map(n=>`<span>${n}</span>`).join('<i>→</i>')}</div><div class="research-detail" aria-live="polite" aria-atomic="true"><h3 id="dimensionTitle">${d[0].name}</h3><p id="dimensionDetail">${d[0].question} ${d[0].method} Example: ${d[0].example}</p></div></div></div></div></section>`}
function watchHTML(){const videos=require('../content/videos.json');const timing=require('../content/video-timings.json');return `<section id="watch" class="paper"><div class="wrap"><div class="kicker">Build notes, in motion</div><h2 class="h1">Watch me explain my work.</h2><div class="watch-heading"><img src="linkedin-avatar.webp" alt="Ritesh Mamidi" width="64" height="64" loading="lazy"><p>Engineering explanations prepared from my repositories, with synchronized English captions and a stock synthetic narrator. The diagrams illustrate the implementation; they are not live telemetry or experimental results.</p></div><div class="watch-grid">${videos.map(v=>`<article class="watch-card"><video controls preload="none" playsinline poster="${mediaURL(v.poster+'-poster.webp')}" aria-label="${escape(v.title)}"><source src="${mediaURL(v.id+'.mp4')}" type="video/mp4"><track kind="captions" src="${mediaURL(v.id+'.vtt')}" srclang="en" label="English" default>Your browser cannot play this video. <a href="assets/media/${v.id}.mp4">Download the video</a>.</video><div class="watch-copy"><div class="watch-meta">${timing[v.id].duration} seconds · Synthetic narration · English captions</div><h3>${v.title}</h3><p>${v.scenes[0].detail}</p><a href="https://github.com/riteshmamidi0905-lab/${v.repo}">Inspect the repository ↗</a> · <a href="assets/media/${v.id}.vtt" download>Captions ↓</a></div></article>`).join('')}</div><p class="watch-deep">Illustrative workflows · No generated footage of Ritesh · No personal voice cloning</p></div></section>`}
module.exports={researchHTML,watchHTML};
